# Welcome to Jekyll!
# .
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. 
# If you find yourself editing this file very often, consider using Jekyll's
# data files feature for the data you need to update frequently.
# 
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# --- Build settings ---
markdown: kramdown
theme: jekyll-theme-leap-day
remote_theme: pages-themes/leap-day@v0.2.0
lang: "en-AU"  # Use "en-US" or other locale code as needed

# --- Site identity ---
title: "| ǝuo ɔᴉɹʇuǝɔɔǝ ǝɥ┴ |"
# Write an awesome description for your new site here. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: Just some thoughts, musings and observatiions from the boundary of tech & curiosity. 
# >- #block_strip: This entire block of text will be the value of 'description', all newlines will be replaced with a single space and trailing blank lines being stripped. This means it will ignore newlines until "baseurl:"
baseurl: "/"                     # e.g. /blog if your site is at example.com/blog
domain: xntrek.github.io        # Forces HTTPS when using GitHub Pages
url: "https://xntrek.github.io" # The base hostname and protocol for your site
logo: /assets/images/logo.png

# --- SEO and meta ---
author: "xntrek"
# email: "your@email.com"
# twitter_username: "your_twitter"
# github_username:  jekyll

# --- GitHub & Theme Integration ---
github:
  is_project_page: true    # Enables "Maintained by" footer
  repository_name: "xntrek.github.io"
  owner_name: "xntrek"
  owner_url: "https://github.com/xntrek"
  repository_url: "https://github.com/xntrek/xntrek.github.io"
  project_tagline: "ooh, what's this button d"
  build_revision: ""       # Leave blank, auto-set by GH Pages on deploy
  show_downloads: false      # Set to true to show .zip/.tar links
# zip_url: "https://github.com/xntrek/xntrek.github.io/archive/refs/heads/main.zip"
# tar_url: "https://github.com/xntrek/xntrek.github.io/archive/refs/heads/main.tar.gz"
  
# --- Custom variables (optional) ---
# custom_var: "Any value you want"
  page_excerpts: true

plugins:
  - jekyll-sitemap
#  - jekyll-menus
#  - jekyll-spaceship
  - jekyll-gfm-admonitions
#  - jekyll-admin
  - jekyll-remote-theme

#  - jekyll-feed
#  - jekyll-toc
#  - jekyll-seo-tag
#  - htmlbeautifier
#  - jekyll-tidy



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

premonition:
  types:
    custom:
      meta:
        fa-icon: fa-business-time
