# --- Site identity ---
title: "| ǝuo ɔᴉɹʇuǝɔɔǝ ǝɥ┴ |"
description: Just some thoughts, musings and observatiions

lang: "en-AU"  # Use "en-US" or other locale code as needed
logo: /assets/images/logo.svg

# --- GitHub & Theme Integration ---
show_downloads: false      # Set to true to show .zip/.tar links
github:
  is_project_page: true    # Enables "Maintained by" footer
  repository_name: "xntrek.github.io"
  owner_name: "xntrek"
  owner_url: "https://github.com/xntrek"
  repository_url: "https://github.com/xntrek/xntrek.github.io"
  project_tagline: "from the boundary of tech & curiosity"
  build_revision: ""       # Leave blank, auto-set by GH Pages on deploy
  # zip_url: "https://github.com/xntrek/xntrek.github.io/archive/refs/heads/main.zip"
  # tar_url: "https://github.com/xntrek/xntrek.github.io/archive/refs/heads/main.tar.gz"
  
# --- SEO and meta ---
domain: xntrek.github.io        # Forces HTTPS when using GitHub Pages
url: "https://xntrek.github.io" # The base hostname and protocol for your site
baseurl: ""                     # e.g. /blog if your site is at example.com/blog
author: "xntrek"
# email: "your@email.com"
# twitter_username: "your_twitter"

# --- Build settings ---
markdown: kramdown
theme: jekyll-theme-leap-day    # Use only if not using remote_theme
#remote_theme: pages-themes/leap-day@v0.2.0

plugins:
  - jekyll-seo-tag
#  - jekyll-remote-theme


# --- Custom variables (optional) ---
# custom_var: "Any value you want"
