remote_theme: pages-themes/leap-day@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "| ǝuo ɔᴉɹʇuǝɔɔǝ ǝɥ┴ |"

description: ǝuO ɔᴉɹʇuǝɔɔƎ ǝɥ┴ ɯoɹɟ sƃuᴉsnɯ puɐ suoᴉʇɐʌɹǝsqo 'sʇɥƃnoɥʇ ǝɯos ʇsnſ

show_downloads: false

google_analytics:

theme: jekyll-theme-leap-day

